<?php
/**
 * Elementor tree diff engine.
 *
 * Walks two Elementor element arrays (before/after) and emits a list of
 * operations: added, removed, modified, and moved. Designed so a UI can
 * preview changes before applying them via MCP_Page_Builder::update()
 * or MCP_Importer::import().
 *
 * Diff is element-id keyed. IDs are expected to be stable across the
 * two trees (regenerated by MCP_Importer when needed).
 *
 * @package ElementorMCP
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class MCP_Diff_Engine {

    const OP_ADDED     = 'added';
    const OP_REMOVED   = 'removed';
    const OP_MODIFIED  = 'modified';
    const OP_MOVED     = 'moved';
    const OP_UNCHANGED = 'unchanged';

    /**
     * Compute a diff between two element trees.
     *
     * @param array $before
     * @param array $after
     * @param array $opts {
     *     @type int   $max_ops  Hard cap on emitted ops (default 5000).
     *     @type bool  $include_unchanged When true, also emit unchanged nodes.
     * }
     *
     * @return array {
     *     'ops'         => [ ['op'=>..., 'path'=>..., 'before'=>..., 'after'=>..., 'meta'=>...], ... ],
     *     'summary'     => [ 'added'=>N, 'removed'=>N, 'modified'=>N, 'moved'=>N, 'unchanged'=>N ],
     *     'before_size' => int,
     *     'after_size'  => int,
     *     'byte_delta'  => int,
     * }
     */
    public function diff( array $before, array $after, array $opts = array() ) {
        $max_ops = isset( $opts['max_ops'] ) ? max( 1, (int) $opts['max_ops'] ) : 5000;
        $include_unchanged = ! empty( $opts['include_unchanged'] );

        $ops = array();

        $before_index = $this->index_tree( $before );
        $after_index  = $this->index_tree( $after );

        $seen_after = array();

        foreach ( $before_index as $id => $before_node ) {
            if ( isset( $after_index[ $id ] ) ) {
                $after_node = $after_index[ $id ];
                $seen_after[ $id ] = true;

                if ( $before_node['parent'] !== $after_node['parent']
                    || $before_node['index'] !== $after_node['index'] ) {
                    if ( count( $ops ) < $max_ops ) {
                        $ops[] = array(
                            'op'     => self::OP_MOVED,
                            'path'   => $this->path_label( $after_node ),
                            'id'     => $id,
                            'elType' => $after_node['elType'],
                            'before' => array( 'parent' => $before_node['parent'], 'index' => $before_node['index'] ),
                            'after'  => array( 'parent' => $after_node['parent'], 'index' => $after_node['index'] ),
                        );
                    }
                }

                if ( $this->payload_differs( $before_node, $after_node ) ) {
                    if ( count( $ops ) < $max_ops ) {
                        $ops[] = array(
                            'op'     => self::OP_MODIFIED,
                            'path'   => $this->path_label( $after_node ),
                            'id'     => $id,
                            'elType' => $after_node['elType'],
                            'before' => array( 'settings' => $before_node['settings'], 'widgetType' => $before_node['widgetType'] ?? null ),
                            'after'  => array( 'settings' => $after_node['settings'], 'widgetType' => $after_node['widgetType'] ?? null ),
                            'meta'   => array( 'changed_keys' => $this->changed_keys( $before_node['settings'], $after_node['settings'] ) ),
                        );
                    }
                } elseif ( $include_unchanged ) {
                    $ops[] = array(
                        'op'     => self::OP_UNCHANGED,
                        'path'   => $this->path_label( $after_node ),
                        'id'     => $id,
                        'elType' => $after_node['elType'],
                    );
                }
            } else {
                if ( count( $ops ) < $max_ops ) {
                    $ops[] = array(
                        'op'     => self::OP_REMOVED,
                        'path'   => $this->path_label( $before_node ),
                        'id'     => $id,
                        'elType' => $before_node['elType'],
                        'before' => array( 'settings' => $before_node['settings'] ),
                    );
                }
            }
        }

        foreach ( $after_index as $id => $after_node ) {
            if ( isset( $seen_after[ $id ] ) ) {
                continue;
            }
            if ( count( $ops ) < $max_ops ) {
                $ops[] = array(
                    'op'     => self::OP_ADDED,
                    'path'   => $this->path_label( $after_node ),
                    'id'     => $id,
                    'elType' => $after_node['elType'],
                    'after'  => array( 'settings' => $after_node['settings'], 'widgetType' => $after_node['widgetType'] ?? null ),
                );
            }
        }

        $summary = array(
            self::OP_ADDED     => 0,
            self::OP_REMOVED   => 0,
            self::OP_MODIFIED  => 0,
            self::OP_MOVED     => 0,
            self::OP_UNCHANGED => 0,
        );
        foreach ( $ops as $op ) {
            $summary[ $op['op'] ]++;
        }

        $before_bytes = strlen( wp_json_encode( $before ) );
        $after_bytes  = strlen( wp_json_encode( $after ) );

        return array(
            'ops'         => $ops,
            'summary'     => $summary,
            'before_size' => count( $before_index ),
            'after_size'  => count( $after_index ),
            'byte_delta'  => $after_bytes - $before_bytes,
            'truncated'   => count( $ops ) >= $max_ops,
        );
    }

    /**
     * Render a flat human-readable summary line — handy for logs/notifications.
     */
    public function to_text( array $diff ) {
        $s = $diff['summary'];
        $size = sprintf( '%d → %d', $diff['before_size'], $diff['after_size'] );
        $bytes = $diff['byte_delta'];
        $bytes_str = ( $bytes > 0 ? '+' : '' ) . number_format_i18n( $bytes ) . ' B';

        return sprintf(
            '%s nodes: added %d, modified %d, removed %d, moved %d (%s, %s)',
            $size,
            $s[ self::OP_ADDED ],
            $s[ self::OP_MODIFIED ],
            $s[ self::OP_REMOVED ],
            $s[ self::OP_MOVED ],
            $bytes_str,
            $diff['truncated'] ? 'TRUNCATED' : 'complete'
        );
    }

    /* ---------- internals ---------- */

    /**
     * Flatten the tree into [ id => [ parent, index, elType, widgetType, settings, path ] ]
     * where path is a positional breadcrumb like "sections[0].columns[1].widgets[2]".
     */
    private function index_tree( array $elements, $parent = 'root', array $parent_path = array() ) {
        $index = array();
        $i = 0;
        foreach ( $elements as $el ) {
            if ( ! is_array( $el ) || empty( $el['id'] ) ) {
                continue;
            }
            $type = isset( $el['elType'] ) ? $el['elType'] : 'element';
            $path = array_merge( $parent_path, array( $this->plural( $type ) . '[' . $i . ']' ) );

            $node = array(
                'parent'     => $parent,
                'index'      => $i,
                'elType'     => $type,
                'settings'   => isset( $el['settings'] ) ? $el['settings'] : array(),
                'path'       => $path,
            );
            if ( 'widget' === $type && isset( $el['widgetType'] ) ) {
                $node['widgetType'] = $el['widgetType'];
            }
            $index[ $el['id'] ] = $node;

            if ( ! empty( $el['elements'] ) && is_array( $el['elements'] ) ) {
                $children = $this->index_tree( $el['elements'], $el['id'], $path );
                $index = array_merge( $index, $children );
            }
            $i++;
        }
        return $index;
    }

    private function payload_differs( array $a, array $b ) {
        if ( ( $a['elType'] ?? null ) !== ( $b['elType'] ?? null ) ) {
            return true;
        }
        if ( ( $a['widgetType'] ?? null ) !== ( $b['widgetType'] ?? null ) ) {
            return true;
        }
        return wp_json_encode( $a['settings'] ) !== wp_json_encode( $b['settings'] );
    }

    private function changed_keys( array $a, array $b ) {
        $keys = array_unique( array_merge( array_keys( $a ), array_keys( $b ) ) );
        $changed = array();
        foreach ( $keys as $k ) {
            $av = $a[ $k ] ?? null;
            $bv = $b[ $k ] ?? null;
            if ( wp_json_encode( $av ) !== wp_json_encode( $bv ) ) {
                $changed[] = (string) $k;
            }
        }
        sort( $changed );
        return $changed;
    }

    private function path_label( array $node ) {
        return implode( '.', $node['path'] );
    }

    private function plural( $type ) {
        switch ( $type ) {
            case 'section': return 'sections';
            case 'column':  return 'columns';
            case 'widget':  return 'widgets';
            default:        return $type . 's';
        }
    }
}